baseURL: https://evelynwunder.de
languageCode: de
title: Evelyn Wunder
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: 

# Menu items
menu:
  main: [{}]

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Evelyn Wunder
  rootUrl: /